### ISSUE TITLE
Russian client, DBM font issue

### ISSUE THREAD

**Issue by rlex** [RealUI/RealUI#15]
Displays "?????????" instead of proper glyphs. 
Probably worth switching default DBM font to something with cyrillic support?

**Comment by rlex** [comment]
Here is nice and open-source font with nice glyphs coverage: http://www.fontsquirrel.com/fonts/notcouriersans
I'm not sure about what's needed for WoW fonts, but hopefully this will help.

**Comment by Gethe** [comment]
Do you have a screenshot?

The DBM timer skin for RealUI is [here](https://github.com/Gethe/nibRealUI_BossSkins), and the font it uses was specificly chosen because it does support cyrrillic fonts.

**Comment by rlex** [comment]
yes, sure. 
I even switched font to roboto in /dbm and done /reloadui, same issue.

You can see "Strangle" cooldown in DBM, with "?????" instead of my name.

![wow-64 2015-11-10 20-39-12-542](https://cloud.githubusercontent.com/assets/84462/11070277/e0041e8e-87eb-11e5-8e19-c613723507b3.jpg)

**Comment by Gethe** [comment]
What are you using to get DBM timers for personal CDs? I don't think that's a standard feature.

Using just the test bars they are showing the correct font, even after a reload. 
![pic](http://i.imgur.com/7xm3INM.jpg)

**Comment by rlex** [comment]
It's DBM spelltimers. But i also tried with same test method you use:
![wow-64 2015-11-10 21-51-13-818](https://cloud.githubusercontent.com/assets/84462/11072101/529e592e-87f5-11e5-9689-f61f36a89409.jpg)
I'll try to competely wipe addons and reinstall them, maybe something is broken in my setup.
