### ISSUE TITLE
Bank Reagent tab displays even when not purchased

### ISSUE THREAD

**Issue by Sleaker** [RealUI/RealUI#17]
The Bank Reagent frame always displays even if your character has not purchased the reagent portion yet. It also displays the purchase button, but it is underneath a bunch of bag slots that you don't have access to yet making it very difficult to click. There's about a 1px area that you can get to that allows you to click it.

cbniv settings: Bank filter off, empty compression off.

**Comment by Gethe** [comment]
Apologies for not responding to this sooner, but at the very least the issue seems to be resolved as i'm not having any issue clicking the purchase button.

Also, it's intended that the reagent bank is shown even without having purchased it
