### ISSUE TITLE
No chat notification for obtained transmog/appearence.

### ISSUE THREAD

**Issue by christiaangieles** [RealUI/RealUI#30]
### Description ###

No chat notification for obtained transmog/appearence.

### Steps to Reproduce ###

1. Loot an item with a skin you don't have.
2. Gain the skin, by equipping or obtaining (BoP)
3. Recieve no chat notification that you've gained the new skin.

**Expected behavior:**

The expected behaviour is that your gonna see it in chat.

**Actual behavior:**

Nothing in chat, or it bugs out with a error (though, I've not had that bug since 17c.

**Installed AddOns:**

Only RealUI and DBM.

**Comment by christiaangieles** [comment]
NOTE: I actually only have RealUI installed right now, and same result.

**Comment by Gethe** [comment]
If you disable PhanxChat, do they come up?

**Comment by christiaangieles** [comment]
No. Just checked twice. Even went as far as too turn on all notifications and options in there.

**Comment by Gethe** [comment]
Just tested some BoEs without any addons, and didn't get a notification. I think this is Blizzard's issue

**Comment by christiaangieles** [comment]
I'm a bit busy tonight, but I'll help you out with some troubleshooting when I get done. Maybe it's a chat option issue, or a "Blizz issue" as you said.

**Comment by christiaangieles** [comment]
Appearently this is on Blizzard's side. Only Epic's get the chat notification. Consider this issue resolved. But hey, if you can make other than Epic+ show in chat, that would've been awesome :+1:

**Comment by Gethe** [comment]
I'll keep it in mand for later, but until then there is an addon called InspectorGadgetzan that does this plus other transmog stuff.
