### ISSUE TITLE
Are you OK? Resolution question.

### ISSUE THREAD

**Issue by Tamashi** [RealUI/RealUI#32]
Hey Gethe, I read something about you no being well. Are you discontinuing the UI? I absolutely love it. My husband has bought me a 3440x1440 resolution monitor (asus rog, 34").

This look bigger than usual, do you support this resolution?

**Comment by Gethe** [comment]
Where did you hear that? I'm doing fine and RealUI won't be discontinued.


You new monitor should be ok, though frames might look a bit small due to the ui scale.
