### ISSUE TITLE
cargBags_Nivaya issue with battle pet

### ISSUE THREAD

**Issue by solor** [RealUI/RealUI#33]
since new commits about cargBags_Nivaya from master branch
i'm having this error when i put a battle pet into cage
and can't find it in the bag
only happen when there is a battle pet in the bag

![wow-64 2016-08-08 14-44-50](https://cloud.githubusercontent.com/assets/156806/17471568/ceacb7ba-5d77-11e6-99f2-a8178c6e788b.png)

**Comment by Gethe** [comment]
The line numbers in that error do not correspond to what is in the latest file. Try deleting the addon before copying it to your addons folder.

**Comment by solor** [comment]
sorry, my mistake.
