### ISSUE TITLE
Artifact UI not opening

### ISSUE THREAD

**Issue by rlex** [RealUI/RealUI#34]
### Prerequisites ###

* [ x ] Are you running the [latest version of RealUI](http://www.wowinterface.com/downloads/fileinfo.php?id=16068)?
* [ x ] Did you check the [debugging guide](http://www.wowinterface.com/forums/showthread.php?t=50089)?
* [ x ] Did you check the [FAQ on WoWInterface](http://www.wowinterface.com/forums/showthread.php?t=49946)?
* [ x ] Did you perform a cursory search [on the forums](http://www.wowinterface.com/forums/search.php?f=163) and [the issue tracker](https://github.com/RealUI/RealUI/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?

### Description ###

http://www.wowinterface.com/forums/showthread.php?t=54341

### Steps to Reproduce ###

1. Get an artifact?
2. Try to open artifact customization menu (either on character or in forge)
3. Get error

**Expected behavior:**

Artifact customization menu should open

**Actual behavior:**

Nothing happens

``` lua
49x FrameXML\MainMenuBar.lua:126: Usage: GetCostForPointAtRank(rank)
[C]: in function `GetCostForPointAtRank'
FrameXML\MainMenuBar.lua:126: in function <FrameXML\MainMenuBar.lua:124>
...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0-5.lua:234: in function <...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:229>
...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0-5.lua:295: in function <...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:282>
...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0-5.lua:396: in function `?'
...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0-5.lua:67: in function <...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:67>
 
Locals:
(*temporary) = nil
```

This is error which is not present at forum reports:

``` lua
20x ...eAuroraBlizzard_ItemAlterationUI.lua:3: attempt to index local 'C' (a nil value)
...eAuroraBlizzard_ItemAlterationUI.lua:3: in main chunk
 
Locals:
F = nil
C = nil
(*temporary) = 2
(*temporary) = "Aurora"
(*temporary) = "attempt to index local 'C' (a nil value)"
```

### Additional information ###

* Problem started happening recently, didn't happen in an older version of RealUI: N/A
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Installed AddOns:**

DBM, AtlasLoot

**Comment by Gethe** [comment]
Fixed in 8.1_r18d

**Comment by rlex** [comment]
Sadly not solved for me - same errors.

**Comment by rlex** [comment]
i'm at RU_ru locale, maybe that's the reason.
