### ISSUE TITLE
Update carg_bags

### ISSUE THREAD

**Issue by stokbaek** [RealUI/RealUI#43]
### Prerequisites ###

* [x] Are you running the [latest version of RealUI](http://www.wowinterface.com/downloads/fileinfo.php?id=16068)?
* [ ] Did you check the [debugging guide](http://www.wowinterface.com/forums/showthread.php?t=50089)?
* [x] Did you check the [FAQ on WoWInterface](http://www.wowinterface.com/forums/showthread.php?t=49946)?
* [x] Did you perform a cursory search [on the forums](http://www.wowinterface.com/forums/search.php?f=163) and [the issue tracker](https://github.com/RealUI/RealUI/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/RealUI/RealUI/blob/master/CONTRIBUTING.md#submitting-a-good-bug-report) or [enhancement request](https://github.com/RealUI/RealUI/blob/master/CONTRIBUTING.md#submitting-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description ###

Would it be possible to bump the bag addon to the newest version of the standalone bag addon that include a section for AP items.

**Comment by Gethe** [comment]
no
