### ISSUE TITLE
Artifact Pane Erros

### ISSUE THREAD

**Issue by overtheandyhill** [RealUI/RealUI#46]
Cannot open artifact pane or forge. Weapon is greyed out in character pane.

Bugger reports:

20x FrameXML\MainMenuBar.lua:125: Usage: local cost = C_ArtifactUI.GetCostForPointAtRank(rank, tier)
[C]:: in function 'GetCostForPointAtRank'
FrameXML\MainMenuBar.lua:125: in function <FrameXML\MainMenuBar.lua:123>
...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0-9.lua:235: in function <...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:226>
...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0-9.lua:296: in function <...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:283>
...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0-9.lua:315: in function <...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:314>

Have isolated down to nibRealUI

Have tried multiple versions of LibArtifactData - disabling nibRealUI alone solves problem.

**Comment by Gethe** [comment]
That version of the library is out of date. the version that RealUI includes is 15, your's is showing 9. Make sure you have the most recent version of RealUI.
