### ISSUE TITLE
#INF% Error with Artifact Power

### ISSUE THREAD

**Issue by Caluril** [RealUI/RealUI#47]
### Prerequisites ###

* [ ] Are you running the [latest version of RealUI](http://www.wowinterface.com/downloads/fileinfo.php?id=16068)? Yes (8.1_r20f)

* [ ] Did you check the [debugging guide](http://www.wowinterface.com/forums/showthread.php?t=50089)? Yes

* [ ] Did you check the [FAQ on WoWInterface](http://www.wowinterface.com/forums/showthread.php?t=49946)? Yes

* [ ] Did you perform a cursory search [on the forums](http://www.wowinterface.com/forums/search.php?f=163) and [the issue tracker](https://github.com/RealUI/RealUI/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported? Yes, Searched on the forums and there's no discussion of anything to do with Artifact Power #INF% issue.
Yes, I have searched this github before submitting this issue.

### Description ###

During Leveling from 100 - 109 the tool bar AP worked, soon as I hit 110 Artifact in the millions or billions seems to break this Artifact Bar, thus showing #INF%.

[Blades of the Fallen Prince] gains 1,260,000,200 Artifact Power.
[Lua Error: 000001E29F769000]

### Steps to Reproduce ###

1. Get Artifact Power Item e.g: Glittering Memento with at least 150 Million or more.
2. Right click on Item in your inventory.
3. Hover mouse over Artifact Power Datatext #INF% or Alt + Left click until Artifact Power data text.
4. Left Click on [LUA Error:000001E29F769000] in the chat.

**Expected behavior:**

To see amount of Artifact Power gained as a bar that fills.

**Actual behavior:**
Datatext shows as #INF%, not very helpful.

`x1  integer overflow attempting to store 1.#INF
Stack: [C] in function 'format'
nibRealUI\Infobar\Blocks.lua:1575: in function 'SetTooltip'
nibRealUI\Infobar\Blocks.lua:1774: in function 'OnEnter'
nibRealUI\Infobar\Bar.lua:62: in function <nibRealUI\Infobar\Bar.lua:47>
Time: 2018/01/01 23:43:16 Index: 1/1
Locals:
(*temporary) = "%s/%s (%d%%)"
(*temporary) = "8,437,342,080"
(*temporary) = "0"
(*temporary) = 1.#INF`

### Additional information ###

* Problem started happening recently, didn't happen in an older version of RealUI: Yes, Started recently, No didn't happen in an older version.
* Problem can be reliably reproduced, doesn't happen randomly: Yes the problem can be reproduced. No it doesn't happen randomly.

**Screenshots and GIFs**

https://screencast-o-matic.com/watch/cFVV2FoVX7

**Installed AddOns:**

Altohilic (Disabled)
Badboy (Disabled)
Badboy - CCleaner (Disabled)
Badboy - Guilded (Disabled)
Badboy - Ignore (Disabled)
Bagsync (Disabled)
DugiGuidesViewer 8.510 (Disabled)
Garrison Mission Manager (Disabled)
HandyNotes (Disabled)
HandyNotes - Argus (Disabled)
HandyNotes - Legion Class Order Halls (Disabled)
HandyNotes - Camel Figurines (Disabled)
HandyNotes - DraenorTreasures (Disabled)
HandyNotes - Guild (Disabled)
HandyNotes - Legion R&T (Disabled)
HandyNotes - Mail Boxes (Disabled)
HandyNotes - Pandaria Treasures (Disabled)
HandyNotes - Suramar Leylines (Disabled)
HandyNotes - Suramar Telemancy (Disabled)
HandyNotes - Trainers (Disabled)
Hide Order Hall Bar (Disabled)
Personal Loot Helper (Disabled)
Postal (Disabled)
Semi-Auto Looter (Disabled)
World Boss Status (Disabled)
World Quest Group Finder (Disabled)
World Quest List (Disabled)
DBM (Disabled)

I also tried removing these addons with no prevail.

**Comment by BlushBerry** [comment]
Can confirm, Getting these bugs among other things which is resulting in Lua errors as well.

**Comment by Caluril** [comment]
Another issue, the time is +30 mins in front of my windows local time ???.
Other than these bugs this is a good ui.

**Comment by Gethe** [comment]
So this only started happening after hitting 110? Is it still happening after logging out?

**Comment by Caluril** [comment]
I tried absolutely everything.
1. Logged out.
2. Exited the game.

At one point I went back to ElvUI, but this haunted me a bit.
So, I deleted my WTF folder and it then started to work, just got it to work last night.
So it seems there may have been a corruption in the lua's somewhere in the WTF folder since reaching max level.
