### ISSUE TITLE
Remove ancillary addons

### ISSUE THREAD

**Issue by Gethe** [RealUI/RealUI#52]
These will be removed from the download, but will be linked to in a "Suggested Additions" section of download page/README

* BadBoy
* Clique
* Skada

**Comment by ItsMattTrevino** [comment]
Tojaso1 posted on May 10th on the [Raven plugin page](https://www.curseforge.com/wow/addons/raven?comment=2411):
> At this point, I am no longer playing WoW. I don't plan to add new features to Raven. I may also find it difficult to reproduce reported errors. And, furthermore, without a subscription it is impossible to run my full test suite so I doubt that I will make another release.

This seems like it may become an issue down the line if it's no longer being maintained. I know the comment itself is fairly new and it may change. Something to keep in mind moving forward with Raven being bundled with RealUI.
