### ISSUE TITLE
RealUI_Inventory

### ISSUE THREAD

**Issue by Gethe** [RealUI/RealUI#60]
This will be a new addon, replacing cargBags_Nivaya. Features planned include:
- [x] Categorized bags and bank
- [x] Auto-sell junk
- [x] Custom categories
- [x] Custom bag order
- [x] Re-assign an items' category
- [x] Reagent Bank

Possible features:
- [ ] Void Storage?

**Comment by himlaklar** [comment]
I just want to chip in and say I'd love to keep the option to make custom categories. Or at least some predefined (but unused in the standard setup) that you can utilize.

**Comment by Hellzbellz123** [comment]
search by item type per proffesion? is that even possible?
like searching for Herbalism mats or blacksmithing mats?

**Comment by ItsMattTrevino** [comment]
As I've made a fork and updated cargBags_Nivaya to be able to auto-sort certain items as well as moved certain blocks to a third column so as not to wind up with an unnecessarily squished inventory, I'd love for a smarter auto-sorting capability as well as more than the two columns that ship with the current inventory. We need more control for larger inventories, not less room.

**Comment by ItsMattTrevino** [comment]
I've forked RealUI for the purposes of updating cargBags_Nivaya (adding a third sortable column and smarter loot filters). If the new inventory plugin that is supposed to replace cargBags is lacking custom categories, sorting (and **more** space to sort within) then this will be a step back.

**Comment by ItsMattTrevino** [comment]
I've forked RealUI for the purposes of updating cargBags_Nivaya (adding a third sortable column and smarter loot filters). If the new inventory plugin that is supposed to replace cargBags is lacking custom categories, better sorting, and **more** space to sort within, then this will be a step back.

**Comment by ItsMattTrevino** [comment]
I've forked RealUI for the purpose of updating cargBags_Nivaya (adding a third sortable column and smarter loot filters). If the new inventory plugin that is supposed to replace cargBags is lacking custom categories, sorting (and **more** space to sort within) then this will be a step back.

**Comment by ItsMattTrevino** [comment]
I've forked RealUI for the purpose of updating cargBags_Nivaya (adding a third sortable column and smarter loot filters). If the new inventory plugin that is supposed to replace cargBags is lacking custom categories, sorting, and **more** space to sort within, then this will be a step back.

**Comment by Gethe** [comment]
Hey, feel free to submit a pull request with your changes. Would be good to get a few improvements in until I can get to the new addon.

**Comment by ItsMattTrevino** [comment]
I've noticed that Blizzard classifies some items wrong (for instance, despite having no recipes and **not** being reagents, Shimmering Minnow and Slippery Eel are classified as Tradegoods->Cooking).

**Comment by Gethe** [comment]
That could be because they can still be eaten "raw" for health regen.

**Comment by ItsMattTrevino** [comment]
Seems more appropriate for them to be labeled as consumables instead of lumped in with the cooking ingredients. Probably not a huge issue or anything, just something that kind of irked me about the way these items get classified on their end.
