### ISSUE TITLE
Barber shop zoomed in 2.2.3+

### ISSUE THREAD

**Issue by MisatoTremor** [RealUI/RealUI#70]
### Prerequisites ###

* [x] Are you running the [latest version of RealUI](http://www.wowinterface.com/downloads/fileinfo.php?id=16068)?
* [x] Did you check the [debugging guide](http://www.wowinterface.com/forums/showthread.php?t=50089)?
* [x] Did you check the [FAQ on WoWInterface](http://www.wowinterface.com/forums/showthread.php?t=49946)?
* [x] Did you perform a cursory search [on the forums](http://www.wowinterface.com/forums/search.php?f=163) and [the issue tracker](https://github.com/RealUI/RealUI/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?

### Description ###

Barber shop zoomed in to much

### Steps to Reproduce ###

1. Enter barber shop chair

**Expected behavior:**

All customization elements visible, no overlap

**Actual behavior:**

Some elements off screen and overlaping

Also on changing an option, the reset button partially resets to the default Blizzard skin

### Additional information ###

* Problem started happening recently, didn't happen in an older version of RealUI: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Screenshots and GIFs**

![WoWScrnShot_101520_103006](https://user-images.githubusercontent.com/3536384/96099066-1ea5c200-0ed3-11eb-944f-57cc50e3aeaa.jpg)

**Installed AddOns:**

-

**Comment by Gethe** [comment]
This is an odd bug. I've tried a number of different resolutions, but in every case the options list has always been vertically centered. Do you happen to have any other addons the interact with the barbershop?

**Comment by MisatoTremor** [comment]
I tried this on 1920x1080 only and also with all non RealUI addons disabled to no avail.
When disabling RealUI too (aka no addons loaded at all) the barber shop is not cut off.

In hindsight "zoomed in" is misleading, actually the UI scale is simply higher

**Comment by MisatoTremor** [comment]
New fix causes this:
![WoWScrnShot_122720_165349](https://user-images.githubusercontent.com/3536384/103174646-35b64800-4864-11eb-9f8f-20afbeb97816.jpg)
![WoWScrnShot_122720_165355](https://user-images.githubusercontent.com/3536384/103174651-3a7afc00-4864-11eb-9547-cd1e2169c162.jpg)

**Comment by Gethe** [comment]
I honestly don't understand how your getting this issue. I've tried different resolutions, different UI scale, and nothing gets even close to what your showing.
![WoWScrnShot_122720_173427](https://user-images.githubusercontent.com/175624/103181725-e8d57000-4869-11eb-98da-43cec4d4df00.jpg)

**Comment by MisatoTremor** [comment]
I really don't understand it either, because I can't remember having this issue prior to WoW 9.0.1 / RealUI 2.2.2, but I also haven't visited the barber shop for some months before the patch.

I also don't think this warrants more time on your end and I will investigate further on my end and report if I find something.
