### ISSUE TITLE
Keybind error?  Can't tell what this is.

### ISSUE THREAD

**Issue by MightBeChris** [RealUI/RealUI#73]
### Prerequisites ###

* [yes] Are you running the [latest version of RealUI](http://www.wowinterface.com/downloads/fileinfo.php?id=16068)?
* [yes ] Did you check the [debugging guide](http://www.wowinterface.com/forums/showthread.php?t=50089)?
* [yes] Did you check the [FAQ on WoWInterface](http://www.wowinterface.com/forums/showthread.php?t=49946)?
* [yes] Did you perform a cursory search [on the forums](http://www.wowinterface.com/forums/search.php?f=163) and [the issue tracker](https://github.com/RealUI/RealUI/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/RealUI/RealUI/blob/master/CONTRIBUTING.md#submitting-a-good-bug-report) or [enhancement request](https://github.com/RealUI/RealUI/blob/master/CONTRIBUTING.md#submitting-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description ###

[Short description of problem here]
There is an error thrown on keybinding

### Steps to Reproduce ###

1. Log in
2. See an error appear that displays as related to "Key Binding"
3. [Other Steps...]

**Expected behavior:**

That an error would not be thrown

**Actual behavior:**

That an error is thrown

``` 
x1  nibRealUI\Modules\Bindings.lua:659: bad argument #1 to 'format' (string expected, got table)
Stack: [string "=[C]"]: in function 'format'
[string "@nibRealUI\Modules\Bindings.lua"]:659: in function 'func'
[string "@nibRealUI\Modules\InterfaceTweaks.lua"]:66: in function '?'
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function 'Fire'
[string "@Ace3\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>
Time: 2020/12/27 17:00:09 Index: 1/1
RealUI Version: 2.2.5
Locals:
None
```

### Additional information ###

* Problem started happening recently, didn't happen in an older version of RealUI: [Yes] 
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Screenshots and GIFs**

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

**Installed AddOns:**
Real Ui
AdiBags
Prat

**Comment by dotted** [comment]
I'm seeing the same error on login, it seems like mine and probably your client is storing a table in `_G["L"]` which causes the error you see. The table seems to there regardless of any addons being loaded, however when I launch the game on my US account `_G["L"]` is nil resulting in no error, so I wonder if this error is specific to the EU client.

**Comment by MightBeChris** [comment]
I'm on the US client so that idea is out. :(

**Comment by dotted** [comment]
I took another look at it, disregard my previous comment entirely. Do you have the addon "Addon Control Panel" installed?

**Comment by MightBeChris** [comment]
I do.  Is that what's throwing it?

**Comment by dotted** [comment]
It seems like ACP sets the global `_G["L"]` which causes issues for RealUI, so the workaround for now would simply be to disable ACP.

**Comment by MightBeChris** [comment]
Aces, thank you!
