### ISSUE TITLE
Error while talking to enchanting trainer

### ISSUE THREAD

**Issue by arnvid** [RealUI/RealUI#75]
### Prerequisites ###

* [yes ] Are you running the [latest version of RealUI](http://www.wowinterface.com/downloads/fileinfo.php?id=16068)?

### Description ###

Error came while buying new skills at the vendor.

### Steps to Reproduce ###

1.  Just buying new skills

``` lua
x33  ItemVersion\Tooltip.lua:16: bad argument #1 to 'strmatch' (string expected, got nil)
Stack: [string "=[C]"]: in function 'strmatch'
[string "@ItemVersion\Tooltip.lua"]:16: in function <ItemVersion\Tooltip.lua:14>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function 'SetTrainerService'
[string "*:OnEnter"]:3: in function <[string "*:OnEnter"]:1>
Time: 2021/01/12 11:39:00 Index: 3/3
Locals:
(*temporary) = nil
(*temporary) = ":(%w+)"
(*temporary) = "string expected, got nil"
```

**Comment by Gethe** [comment]
I'm not sure this is due to RealUI. Try disabling ItemVersion

**Comment by arnvid** [comment]
@Gethe - filed it on the ItemVersion github .. looking at the code there should propably be a check if string is empty or not.
